### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by kishlaya** [Boettner-eric/Tiles#6]
https://github.com/Boettner-eric/Tiles/blob/9f54439daa9d34f1e2551da7e822c4057cd16523/keys.js#L112

The variable 'liverpool' is undefined. (although it is never referenced as @f never occurs on any tile url)

Did you plan to have football scores also on some tile?

**Comment by Boettner-eric** [comment]
@kishlaya Ya there is a version that I have been working on that has more expansive api support (live sport scores, more weather and stock info). This must have just snuck through the public version

**Comment by kishlaya** [comment]
Oh, okay. In that case, I will just close this issue.
