### ISSUE TITLE
Bug in next page command

### ISSUE THREAD

**Issue by kishlaya** [Boettner-eric/Tiles#7]
https://github.com/Boettner-eric/Tiles/blob/9f54439daa9d34f1e2551da7e822c4057cd16523/keys.js#L82

I tried adding more themes. The theme on the "next" page, all threw an error.

**Comment by Boettner-eric** [comment]
@kishlaya Hmmm. When I test it with two pages of themes I can't find the issue.  Can you send the error or a screenshot?

**Comment by kishlaya** [comment]
Can you try the following: Add more themes to your array, say 15, then 10 themes will occur on first page and the other 5 on next page. Now try selecting different themes from the next page multiple times. (The first time you won't get an error).

**Comment by kishlaya** [comment]
Here's the reason behind this error: When you do `.splice`, it changes the original array itself.

When you do `page.splice` first time, your rest of the themes get lost from the Pages["Themes"] array. Hence in the `set_theme` method, you won't get all the themes.
